### ISSUE TITLE
get stuck at `Building pytauri-demo`

### ISSUE THREAD

**Issue by miaoxu1com** [WSH032/pytauri#1]
system info：
Windows 10
22H2
19045.5011

node js version：
![image](https://github.com/user-attachments/assets/26ce1879-df90-4a0c-8918-b21edad584e5)
rust version：
![image](https://github.com/user-attachments/assets/e7d0fb14-c797-4452-b8db-cc6aed8655ca)
cargo version：
![image](https://github.com/user-attachments/assets/e174dfa8-c59b-492d-9d8b-4c0de4ef3de0)
uv pip info：
![image](https://github.com/user-attachments/assets/5d282a60-729d-4d94-be10-fbf76f7eb98f)

python version：
![image](https://github.com/user-attachments/assets/a4fd9d93-f87d-4398-8d13-fdb1388576ea)

window build tools chain：
![image](https://github.com/user-attachments/assets/0c6bba53-bf29-47b5-a99d-4c0f217a1420)

I retried multiple times, but it still gets stuck at 'Building pytauri-demo'.
![image](https://github.com/user-attachments/assets/3bb26602-3faa-4f8e-8379-f896e47d1f69)

**Comment by miaoxu1com** [comment]
@WSH032

**Comment by WSH032** [comment]
Hi @miaoxu1com, actually `uv sync` builds `pytauri` from the local workspace in development mode, which means it requires the Rust compiler to build. The first build needs to compile the dependencies of `pytauri`, which might take a long time.

You can check if the process is still running with the following command:

```diff
- uv sync --no-build-isolation-package=pytauri-demo --reinstall-package=pytauri-demo
+ uv sync --no-build-isolation-package=pytauri-demo --reinstall-package=pytauri-demo -V
```

Once you have completed the first build, you do not need to recompile as long as you do not modify the Rust code. Even if you modify the Rust code, subsequent compilations will be much faster.

**Comment by miaoxu1com** [comment]
Thank you for your response. After retrying, I finally completed the compilation, and the issue has been resolved.

**Comment by miaoxu1com** [comment]
@WSH032

**Comment by miaoxu1com** [comment]
1.How do I compile my project into an .exe file? Is it done through PyInstaller? This way, does it still require the Python interpreter to execute the compiled code?
2.Can a project be compiled into an .exe file using Rust, so that the compiled program does not depend on the Python interpreter?

**Comment by WSH032** [comment]
> How do I compile my project into an .exe file? Is it done through PyInstaller? This way, does it still require the Python interpreter to execute the compiled code?

You can check out these projects:

- [pyinstall]
- [Nuitka]
- [PyOxidizer]

These projects freeze Python code and bundle the Python dynamic library, which means the user environment no longer needs to have Python installed. The generated executable is a combination of the Python interpreter and your code.

[pyinstall]: https://github.com/pyinstaller/pyinstaller
[Nuitka]: https://github.com/Nuitka/Nuitka
[PyOxidizer]: https://github.com/indygreg/PyOxidizer

Additionally, the [pyapp] project can also generate executable files, but it works differently from the above projects. `pyapp` essentially downloads a portable Python interpreter in the user environment and then calls that interpreter to execute the code.

[pyapp]: https://github.com/ofek/pyapp

---

> Can a project be compiled into an .exe file using Rust, so that the compiled program does not depend on the Python interpreter?

`pyapp` and `PyOxidizer` are written in Rust, and their usage requires the Rust compiler.

However, it seems that `PyOxidizer` currently lacks maintenance. If this situation continues, I might implement a Python freezer myself using `pyo3` and `pyapp` in the future.

**Comment by miaoxu1com** [comment]
Tanks，The issue can be closed.

**Comment by WSH032** [comment]
> 2.Can a project be compiled into an .exe file using Rust, so that the compiled program does not depend on the Python interpreter?

[pytauri has already implemented this feature through tauri-cli](https://github.com/WSH032/pytauri/issues/2#issuecomment-2569507310).
